version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongodb:27017/products-crud
    depends_on:
      - mongodb
    networks:
      - mynetwork

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
